/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2024-02-18 11:15:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.rentcar;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class carOption_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Soon/.m2/repository/org/mortbay/jasper/taglibs-standard/10.0.0-M10/taglibs-standard-10.0.0-M10.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-10.0.0-M10.jar", Long.valueOf(1606154388000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Insert title here</title>\r\n");
      out.write("  <style>\r\n");
      out.write("      #reservate-btn {\r\n");
      out.write("          background-color : oklch(0.4912 0.3096 275.75) !important;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #reservate-btn:hover {\r\n");
      out.write("          background-color : oklab(0.44208 0.0279164 -0.277238) !important;\r\n");
      out.write("      }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-100\">\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"reservateCar.do\" method=\"post\" class=\"max-w-2xl mx-auto my-10 bg-white p-5 rounded shadow-md\">\r\n");
      out.write("  <h2 class=\"text-2xl font-bold mb-5 text-gray-900\">옵션 선택</h2>\r\n");
      out.write("  <div class=\"mb-4\">\r\n");
      out.write("    <img src=\"img/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${img}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"w-full h-auto rounded\"/>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"grid grid-cols-2 gap-4\">\r\n");
      out.write("    <div>\r\n");
      out.write("      <label class=\"block text-gray-700\">대여기간</label>\r\n");
      out.write("      <select id=\"dday\" name=\"dday\" class=\"form-select mt-1 block w-full\">\r\n");
      out.write("        <option value=\"1\">1일</option>\r\n");
      out.write("        <option value=\"2\">2일</option>\r\n");
      out.write("        <option value=\"3\">3일</option>\r\n");
      out.write("        <option value=\"4\">4일</option>\r\n");
      out.write("        <option value=\"5\">5일</option>\r\n");
      out.write("        <option value=\"6\">6일</option>\r\n");
      out.write("        <option value=\"7\">7일</option>\r\n");
      out.write("      </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("      <label class=\"block text-gray-700\">대여일</label>\r\n");
      out.write("      <input type=\"date\" name=\"rday\" id=\"rday\" class=\"form-input mt-1 block w-full\" size=\"15\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("      document.getElementById(\"rday\").value = new Date().toISOString().substring(0, 10);\r\n");
      out.write("    </script>\r\n");
      out.write("    <div>\r\n");
      out.write("      <label class=\"block text-gray-700\">보험적용</label>\r\n");
      out.write("      <select id=\"usein\" name=\"usein\" class=\"form-select mt-1 block w-full\">\r\n");
      out.write("        <option value=\"1\">적용(1일 1만원)</option>\r\n");
      out.write("        <option value=\"2\">비적용</option>\r\n");
      out.write("      </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("      <label class=\"block text-gray-700\">Wifi 적용</label>\r\n");
      out.write("      <select id=\"usewifi\" name=\"usewifi\" class=\"form-select mt-1 block w-full\">\r\n");
      out.write("        <option value=\"1\">적용(1일 1만원)</option>\r\n");
      out.write("        <option value=\"2\">비적용</option>\r\n");
      out.write("      </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("      <label class=\"block text-gray-700\">네비게이션 적용</label>\r\n");
      out.write("      <select id=\"usenavi\" name=\"usenavi\" class=\"form-select mt-1 block w-full\">\r\n");
      out.write("        <option value=\"1\">적용(무료)</option>\r\n");
      out.write("        <option value=\"2\">비적용</option>\r\n");
      out.write("      </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("      <label class=\"block text-gray-700\">베이비시트 적용</label>\r\n");
      out.write("      <select id=\"useseat\" name=\"useseat\" class=\"form-select mt-1 block w-full\">\r\n");
      out.write("        <option value=\"1\">적용(1일 1만원)</option>\r\n");
      out.write("        <option value=\"2\">비적용</option>\r\n");
      out.write("      </select>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <input type=\"hidden\" name=\"no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${no}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" id=\"qty\" name=\"qty\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qty}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("  <input type=\"button\" id=\"reservate-btn\" value=\"차량예약하기\" data-no=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${no}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("         class=\"mt-5 text-white font-bold py-2 px-4 rounded\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<dialog id=\"my_modal\" class=\"modal\">\r\n");
      out.write("  <div class=\"modal-box w-11/12 max-w-5xl p-6 bg-white rounded-md\">\r\n");
      out.write("    <h3 class=\"font-bold text-2xl mb-4\">차량 예약 완료 화면</h3>\r\n");
      out.write("    <div class=\"flex justify-center\">\r\n");
      out.write("      <img src=\"img/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${img}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"w-3/4 h-auto\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"text-center mt-4\">\r\n");
      out.write("      <p class=\"text-lg mb-2\">차량 총예약 금액 <span id=\"totalCarValue\"></span></p>\r\n");
      out.write("      <p class=\"text-lg mb-2\">차량 총옵션 금액 <span id=\"totalOptionValue\"></span></p>\r\n");
      out.write("      <p class=\"text-lg mb-2\">차량 총 금액 <span id=\"totalAmountValue\"></span></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-action mt-6\">\r\n");
      out.write("      <form method=\"dialog\">\r\n");
      out.write("        <button\r\n");
      out.write("            class=\"btn bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center\"\r\n");
      out.write("            id=\"close-btn\">\r\n");
      out.write("          <svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\"\r\n");
      out.write("               stroke-linejoin=\"round\" stroke-width=\"2\" viewBox=\"0 0 24 24\" class=\"w-5 h-5 mr-1\">\r\n");
      out.write("            <path d=\"M15 19l-7-7 7-7\"></path>\r\n");
      out.write("          </svg>\r\n");
      out.write("          Close\r\n");
      out.write("        </button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</dialog>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  $(\"#reservate-btn\").click(function () {\r\n");
      out.write("    let query = {\r\n");
      out.write("      no: $(this).data(\"no\"),\r\n");
      out.write("      qty: $(\"#qty\").val(),\r\n");
      out.write("      dday: $(\"#dday\").val(),\r\n");
      out.write("      rday: $(\"#rday\").val(),\r\n");
      out.write("      usein: $(\"#usein\").val(),\r\n");
      out.write("      usewifi: $(\"#usewifi\").val(),\r\n");
      out.write("      usenavi: $(\"#usenavi\").val(),\r\n");
      out.write("      useseat: $(\"#useseat\").val(),\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    $.ajax({\r\n");
      out.write("      type: \"POST\",\r\n");
      out.write("      url: \"reservateCar.do\",\r\n");
      out.write("      data: query,\r\n");
      out.write("      success: function (data) {\r\n");
      out.write("        if (data) {\r\n");
      out.write("          let result = JSON.parse(data);\r\n");
      out.write("          $(\"#totalCarValue\").text(result.totalCar + \" 원\");\r\n");
      out.write("          $(\"#totalOptionValue\").text(result.totalOption + \" 원\");\r\n");
      out.write("          $(\"#totalAmountValue\").text(result.totalAmount + \" 원\");\r\n");
      out.write("\r\n");
      out.write("          document.getElementById('my_modal').showModal();\r\n");
      out.write("          check = true;\r\n");
      out.write("        } else {\r\n");
      out.write("          alert(\"현재 시스템 날짜보다 이전 날짜는 선택할 수 없음\");\r\n");
      out.write("          $(\"#rday\").val(new Date().toISOString().substring(0, 10));\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  document.querySelector(\"#close-btn\").addEventListener(\"click\", (e) => {\r\n");
      out.write("    window.location.href = \"userReserveList.do\";\r\n");
      out.write("  });\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/rentcar/carOption.jsp(23,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("id");
      // /WEB-INF/rentcar/carOption.jsp(23,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/rentcar/carOption.jsp(23,0) '${sessionScope.id}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.id}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/rentcar/carOption.jsp(25,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id eq null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <script type=\"text/javascript\">\r\n");
          out.write("      alert(\"로그인을 먼저 해주세요.\");\r\n");
          out.write("      location.href = 'main.do?center=user/login.jsp';\r\n");
          out.write("    </script>\r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }
}
