/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-02-15 06:12:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class userInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/TJ/.m2/repository/org/mortbay/jasper/taglibs-standard/10.0.0-M10/taglibs-standard-10.0.0-M10.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-10.0.0-M10.jar", Long.valueOf(1606154388000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Title</title>\r\n");
      out.write("  <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"updateUser.do\" method=\"post\" onsubmit=\"userForm_submit(this); return false;\">\r\n");
      out.write("  <input type=\"hidden\" name=\"no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.no}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("  <table>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>번호</td>\r\n");
      out.write("      <td class=\"left\" id=\"no\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.no}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>아이디</td>\r\n");
      out.write("      <td class=\"left\" id=\"id\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>비밀번호</td>\r\n");
      out.write("      <td><input class=\"col-12\" type=\"text\" id=\"pw\" name=\"pw\"/>\r\n");
      out.write("        <input type=\"button\" value=\"비밀번호체크\" id=\"checkPw\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>비밀번호확인</td>\r\n");
      out.write("      <td><input class=\"col-12\" type=\"text\" name=\"pwConfirm\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>이메일</td>\r\n");
      out.write("      <td><input class=\"col-12\" type=\"text\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.email}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>전화번호</td>\r\n");
      out.write("      <td><input class=\"col-12\" type=\"text\" name=\"tel\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.tel}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>취미</td>\r\n");
      out.write("      <td><input class=\"col-12\" type=\"text\" name=\"hobby\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.hobby}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>직업</td>\r\n");
      out.write("      <td><input class=\"col-12\" type=\"text\" name=\"job\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.job}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>나이</td>\r\n");
      out.write("      <td><input class=\"col-12\" type=\"text\" name=\"age\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.age}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>자기소개</td>\r\n");
      out.write("      <td><input class=\"col-12\" type=\"text\" name=\"info\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.info}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td colspan=\"2\" align=\"center\">\r\n");
      out.write("        <input type=\"submit\" id=\"submitBtn\" value=\"수정하기\"/>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td colspan=\"2\" align=\"center\">\r\n");
      out.write("        <input type=\"button\" id=\"delBtn\" value=\"탈퇴하기\"/>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  let userFormSubmitDone;\r\n");
      out.write("  let check = false;\r\n");
      out.write("\r\n");
      out.write("  function userForm_submit(form) {\r\n");
      out.write("    userFormSubmitDone = false;\r\n");
      out.write("    if (!check) {\r\n");
      out.write("      alert('비밀번호를 확인 해주세요');\r\n");
      out.write("      return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (userFormSubmitDone) {\r\n");
      out.write("      alert('처리 중입니다.');\r\n");
      out.write("      return;\r\n");
      out.write("    }\r\n");
      out.write("    form.pwConfirm.value = form.pwConfirm.value.trim();\r\n");
      out.write("\r\n");
      out.write("    if (form.pwConfirm.value.length == 0) {\r\n");
      out.write("      alert('비밀번호 확인을 입력해주세요');\r\n");
      out.write("      form.pwConfirm.focus();\r\n");
      out.write("      return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (form.pw.value != form.pwConfirm.value) {\r\n");
      out.write("      alert('비밀번호가 일치하지 않습니다.');\r\n");
      out.write("      form.pwConfirm.focus();\r\n");
      out.write("      return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    form.email.value = form.email.value.trim();\r\n");
      out.write("    if (form.email.value.length == 0) {\r\n");
      out.write("      alert('이메일을 입력해주세요.');\r\n");
      out.write("      form.email.focus();\r\n");
      out.write("      return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    form.tel.value = form.tel.value.trim();\r\n");
      out.write("    if (form.tel.value.length == 0) {\r\n");
      out.write("      alert('전화번호를 입력해주세요.');\r\n");
      out.write("      form.tel.focus();\r\n");
      out.write("      return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    form.hobby.value = form.hobby.value.trim();\r\n");
      out.write("    if (form.hobby.value.length == 0) {\r\n");
      out.write("      alert('취미를 입력해주세요.');\r\n");
      out.write("      form.hobby.focus();\r\n");
      out.write("      return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    form.job.value = form.job.value.trim();\r\n");
      out.write("    if (form.job.value.length == 0) {\r\n");
      out.write("      alert('직업을 입력해주세요.');\r\n");
      out.write("      form.job.focus();\r\n");
      out.write("      return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    form.age.value = form.age.value.trim();\r\n");
      out.write("    if (form.age.value.length == 0) {\r\n");
      out.write("      alert('나이를 입력해주세요.');\r\n");
      out.write("      form.age.focus();\r\n");
      out.write("      return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    form.info.value = form.info.value.trim();\r\n");
      out.write("    if (form.info.value.length == 0) {\r\n");
      out.write("      alert('자기소개를 입력해주세요.');\r\n");
      out.write("      form.info.focus();\r\n");
      out.write("      return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (check) {\r\n");
      out.write("      form.submit();\r\n");
      out.write("      userFormSubmitDone = true;\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("  $(\"#checkPw\").click(function () {\r\n");
      out.write("    let id;\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("      id = $(\"#id\").text();\r\n");
      out.write("    });\r\n");
      out.write("    let pw = $(\"#pw\").val().trim();\r\n");
      out.write("\r\n");
      out.write("    if (pw.length === 0) {\r\n");
      out.write("      alert(\"pw 값을 입력해주세요\");\r\n");
      out.write("      $(\"#pw\").focus();\r\n");
      out.write("      $(\"#pw\").css(\"border\", \"\");\r\n");
      out.write("      return;\r\n");
      out.write("    }\r\n");
      out.write("    console.log(id);\r\n");
      out.write("    console.log(pw);\r\n");
      out.write("    $.ajax({\r\n");
      out.write("      type: \"POST\",\r\n");
      out.write("      url: \"validateId.do\",\r\n");
      out.write("      data: {\r\n");
      out.write("        id: id,\r\n");
      out.write("        pw: pw\r\n");
      out.write("      },\r\n");
      out.write("      success: getResult,\r\n");
      out.write("      error: function () {\r\n");
      out.write("        alert(\"error\");\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  function getResult(data) {\r\n");
      out.write("    if (data === \"valid\") {\r\n");
      out.write("      alert(\"비밀번호 일치\");\r\n");
      out.write("      check = true;\r\n");
      out.write("    } else if (data === \"notValid\") {\r\n");
      out.write("      alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("      $(\"#pw\").val(\"\");\r\n");
      out.write("      $(\"#pw\").focus();\r\n");
      out.write("      $(\"#pw\").css(\"border\", \"3px red solid\");\r\n");
      out.write("      check = false;\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  $(\"#pw\").keyup(function (e) {\r\n");
      out.write("    // if (e.keyCode === 8) {\r\n");
      out.write("    check = false;\r\n");
      out.write("    // }\r\n");
      out.write("    $(\"#pw\").css(\"border\", \"\");\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  //회원탈퇴\r\n");
      out.write("  $(\"#delBtn\").click(function () {\r\n");
      out.write("    let no;\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("      no = $(\"#no\").text();\r\n");
      out.write("    });\r\n");
      out.write("    $.ajax({\r\n");
      out.write("      type: \"POST\",\r\n");
      out.write("      url: \"deleteUser.do\",\r\n");
      out.write("      data: {no: no},\r\n");
      out.write("      success: getResult,\r\n");
      out.write("      error: function () {\r\n");
      out.write("        alert(\"error\");\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  function getResult(data) {\r\n");
      out.write("    if (data > 0) {\r\n");
      out.write("      alert(\"탈퇴성공\");\r\n");
      out.write("      window.location.href = \"main.do\";\r\n");
      out.write("    } else {\r\n");
      out.write("      alert(\"not quit\");\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
